version: '3.3'

services:
  database:
    image: postgres:16
    environment:
      - POSTGRES_DB=nativApps
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456789
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql